### ISSUE TITLE
django.db.utils.OperationalError: no such column: container_vul.docker_compose_path

### ISSUE THREAD

**Issue by smartzh** [fofapro/vulfocus#185]
**报错信息**
服务器内部错误，请联系管理员
**操作系统**： 
CentOS Linux 7 (Core)

**内核版本**：
3.10.0-1127.el7.x86_64

**Python 环境版本**：
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

**Vulfocus 版本**：

2.3.6
**详细报错信息或堆栈报错信息**：
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/venv_py/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/venv_py/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/venv_py/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/data/venv_py/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/data/venv_py/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/data/venv_py/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/web/vulfocus-api/user/views.py", line 100, in get
    return JsonResponse(serializer.data)
  File "/data/venv_py/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/data/venv_py/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/data/venv_py/lib/python3.8/site-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/data/venv_py/lib/python3.8/site-packages/rest_framework/fields.py", line 1905, in to_representation
    return method(value)
  File "/data/web/vulfocus-api/user/serializers.py", line 57, in rankAD
    for i in successful:
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: container_vul.docker_compose_path
[pid: 1243|app: 0|req: 1/9] 192.168.110.60 () {56 vars in 1291 bytes} [Fri Aug 13 01:23:10 2021] GET /api/user/info => generated 17628 bytes in 657 msecs (HTTP/2.0 500) 4 headers in 145 bytes (1 switches on core 0)

(venv_py) [root@vulfocus log]#

**Comment by Liiuliu** [comment]
@smartzh 请问是在什么什么操作报错的，django.db.utils.OperationalError: no such column: container_vul.docker_compose_path，这像是数据库迁移的问题。

**Comment by smartzh** [comment]
账号登录的时候报的错

**Comment by smartzh** [comment]
经过分析，是db.sqlite3文件没有更新，导致column查询错误，麻烦更新下

**Comment by Liiuliu** [comment]
可以自己迁移数据库，我已经提交更新，等待合并 @smartzh @0nise
