### ISSUE TITLE
 服务器内部错误，请联系管理员(AttributeError: 'str' object has no attribute 'decode' ）

### ISSUE THREAD

**Issue by smartzh** [fofapro/vulfocus#235]
**报错信息**
AttributeError: 'str' object has no attribute 'decode'

**操作系统**： 

**内核版本**：

**Python 环境版本**：

**Vulfocus 版本**：
v0.3.2.11

**详细报错信息或堆栈报错信息**：

(venv_py) [root@vulfocus vulfocus-api]# tail -f /data/log/vulfocus_uwsgi.log
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/features.py", line 82, in is_sql_auto_is_null_enabled
    cursor.execute('SELECT @@SQL_AUTO_IS_NULL')
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/operations.py", line 146, in last_executed_query
    query = query.decode(errors='replace')
AttributeError: 'str' object has no attribute 'decode'
[pid: 1122|app: 0|req: 4/5] 192.168.110.68 () {54 vars in 927 bytes} [Thu Dec 30 19:34:58 2021] GET /api/get/urlname => generated 131342 bytes in 238 msecs (HTTP/2.0 500) 4 headers in 138 bytes (1 switches on core 0)
[pid: 1124|app: 0|req: 1/6] 192.168.110.68 () {54 vars in 933 bytes} [Thu Dec 30 19:34:58 2021] GET /api/get/settingimg => generated 40 bytes in 453 msecs (HTTP/2.0 200) 4 headers in 114 bytes (1 switches on core 0)
Internal Server Error: /api/get/urlname
Traceback (most recent call last):
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/venv_py/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/web/vulfocus-api/dockerapi/views.py", line 1704, in get_url_name
    configs = get_setting_config()
  File "/data/web/vulfocus-api/dockerapi/common.py", line 62, in get_setting_config
    config = SysConfig.objects.filter(config_key=config_key).first()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor = self.connection.cursor()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.init_connection_state()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 231, in init_connection_state
    if self.features.is_sql_auto_is_null_enabled:
  File "/data/venv_py/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/features.py", line 82, in is_sql_auto_is_null_enabled
    cursor.execute('SELECT @@SQL_AUTO_IS_NULL')
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/operations.py", line 146, in last_executed_query
    query = query.decode(errors='replace')
AttributeError: 'str' object has no attribute 'decode'
ERROR:django.request:Internal Server Error: /api/get/urlname
Traceback (most recent call last):
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/venv_py/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/venv_py/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/web/vulfocus-api/dockerapi/views.py", line 1704, in get_url_name
    configs = get_setting_config()
  File "/data/web/vulfocus-api/dockerapi/common.py", line 62, in get_setting_config
    config = SysConfig.objects.filter(config_key=config_key).first()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor = self.connection.cursor()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.init_connection_state()
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 231, in init_connection_state
    if self.features.is_sql_auto_is_null_enabled:
  File "/data/venv_py/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/features.py", line 82, in is_sql_auto_is_null_enabled
    cursor.execute('SELECT @@SQL_AUTO_IS_NULL')
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/operations.py", line 146, in last_executed_query
    query = query.decode(errors='replace')
AttributeError: 'str' object has no attribute 'decode'

**Comment by 0nise** [comment]
确认一下运行的`python`版本

**Comment by smartzh** [comment]
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x7fdcd96f83a0>
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
# extension module 'readline' loaded from '/opt/anaconda3/lib/python3.8/lib-dynload/readline.cpython-38-x86_64-linux-gnu.so'
# extension module 'readline' executed from '/opt/anaconda3/lib/python3.8/lib-dynload/readline.cpython-38-x86_64-linux-gnu.so'
import 'readline' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7fdcd96ca640>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# /opt/anaconda3/lib/python3.8/__pycache__/rlcompleter.cpython-38.pyc matches /opt/anaconda3/lib/python3.8/rlcompleter.py
# code object from '/opt/anaconda3/lib/python3.8/__pycache__/rlcompleter.cpython-38.pyc'
import 'rlcompleter' # <_frozen_importlib_external.SourceFileLoader object at 0x7fdcd213fb80>
>>>

**Comment by x98zy** [comment]
将/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/operations.py这个文件的145,146行注释掉，在安装文档里有说明

**Comment by smartzh** [comment]
好的，谢谢

**Comment by smartzh** [comment]
还有登录的时候报“服务器内部错误，请联系管理员”，看日志找不到表里面user_userprofile字段licence（django.db.utils.OperationalError: (1054, "Unknown column 'user_userprofile.licence' in 'field list'")）

详细信息如下：
(venv_py) [root@vulfocus vulfocus-frontend]#  tail -f /data/log/vulfocus_uwsgi.log
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/data/venv_py/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/data/venv_py/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/data/venv_py/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/data/venv_py/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/data/venv_py/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/data/venv_py/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/data/venv_py/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/data/venv_py/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'user_userprofile.licence' in 'field list'")

The above exception was the direct cause of the following exception:

**Comment by x98zy** [comment]
应该是迁移的时候出了问题，首先将vulfocus-api下面的所有migrations文件夹下面的以00开头的py文件删除，migrations下的__init__.py不要删除，然后执行python manage.py makemigrations,然后执行python manage.py migrate --fake

**Comment by smartzh** [comment]
migrate不报错了，但是下面这个问题还是存在。

还有登录的时候报“服务器内部错误，请联系管理员”，看日志找不到表里面user_userprofile字段licence（django.db.utils.OperationalError: (1054, "Unknown column 'user_userprofile.licence' in 'field list'")）

详细信息如下：
(venv_py) [root@vulfocus vulfocus-frontend]# tail -f /data/log/vulfocus_uwsgi.log
Internal Server Error: /api/login/
Traceback (most recent call last):
File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/data/venv_py/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
return self.cursor.execute(query, args)
File "/data/venv_py/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
result = self._query(query)
File "/data/venv_py/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
conn.query(q)
File "/data/venv_py/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
self._affected_rows = self._read_query_result(unbuffered=unbuffered)
File "/data/venv_py/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
result.read()
File "/data/venv_py/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
first_packet = self.connection._read_packet()
File "/data/venv_py/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
packet.raise_for_error()
File "/data/venv_py/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
err.raise_mysql_exception(self._data)
File "/data/venv_py/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'user_userprofile.licence' in 'field list'")

The above exception was the direct cause of the following exception:

**Comment by smartzh** [comment]
还有就是推出了新版本0.3.2.13,github没有更新

**Comment by Liiuliu** [comment]
可以删除迁移文件，然后换一个数据库重新迁移，就是数据会没有了。 如果本地部署可以把对应字段注释掉后进行迁移，然后在解开再次迁移。如果还是解决不了留个V。

**Comment by smartzh** [comment]
“如果本地部署可以把对应字段注释掉后进行迁移，然后在解开再次迁移。如果还是解决不了留个V。”

抱歉，这句话我没有理解，能详细说下吗？

**Comment by Liiuliu** [comment]
models 文件中对应字段删除掉 然后删除migrations文件夹下面的以00开头的py文件删除 然后迁移 再把对应字段加上再次迁移
